# Handler
handlers=io.helidon.logging.jul.HelidonConsoleHandler

# Format : date heure niveau logger thread: message
java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS.%1$tL %4$s %3$s [!thread!]: %5$s%6$s%n

# Niveau global
.level=INFO

# Niveaux par package ? ajuste selon tes besoins
me.noynto.fortress.level=INFO
io.helidon.webserver.level=INFO
io.helidon.dbclient.level=WARNING
org.flywaydb.level=INFO
com.zaxxer.hikari.level=WARNING
