# Handler
handlers=io.helidon.logging.jul.HelidonConsoleHandler

# Format élégant :
# [HH:mm:ss.SSS] LEVEL  LoggerShortName (thread): message
java.util.logging.SimpleFormatter.format=[%1$tH:%1$tM:%1$tS.%1$tL] %4$-7s [!thread!] %5$s%6$s%n

# Niveau global
.level=INFO

# Niveaux par package
me.noynto.fortress.level=INFO
io.helidon.webserver.level=INFO
io.helidon.dbclient.level=WARNING
io.helidon.logging.level=WARNING
org.flywaydb.level=INFO